"""World State — the single source of truth (GAME_RULES.md §1, §3.1, §6).

The SLM never mutates this directly; only the resolver does, after validating and
clamping the model's proposals.
"""

from __future__ import annotations

from dataclasses import dataclass, field

# --- The 8 universal indicators, 0..100 (GAME_RULES.md §1) -----------------------

INDICATORS = [
    "economy",
    "approval",
    "security",
    "social_cohesion",
    "public_services",
    "fiscal_health",
    "international_power",
    "institutional_stability",
]

INDICATOR_LABELS = {
    "economy": "Economy",
    "approval": "Approval",
    "security": "Security",
    "social_cohesion": "Social cohesion",
    "public_services": "Public services",
    "fiscal_health": "Fiscal health",
    "international_power": "Intl. power",
    "institutional_stability": "Institutions",
}

# --- Country-specific faction meters (GAME_RULES.md §3.1) ------------------------
# Semi-hidden 0..100 meters that drive special endings. MVP details China only.

FACTION_KEYS = ["party_loyalty", "pla_loyalty", "coup_plot_progress"]

# Effects may target an indicator OR a faction meter:
EFFECT_TARGETS = set(INDICATORS) | set(FACTION_KEYS)


def clamp(value: float, lo: int = 0, hi: int = 100) -> int:
    return int(max(lo, min(hi, round(value))))


@dataclass
class Objective:
    """One of the 8 win goals, generated by the SLM but checkable by code (§4, §7.1)."""

    id: str
    title: str
    description: str
    category: str
    indicator: str
    op: str  # ">=", "<=", ">", "<"
    target: int
    by_month: int = 12
    difficulty: str = "medium"

    def is_met(self, state: "WorldState") -> bool:
        v = state.indicators.get(self.indicator, state.factions.get(self.indicator, 0))
        if self.op == ">=":
            return v >= self.target
        if self.op == "<=":
            return v <= self.target
        if self.op == ">":
            return v > self.target
        if self.op == "<":
            return v < self.target
        raise ValueError(f"bad op {self.op!r}")


@dataclass
class WorldState:
    country: str
    month: int = 1  # 1..12 (Jan..Dec 2025)
    indicators: dict[str, int] = field(default_factory=dict)
    factions: dict[str, int] = field(default_factory=dict)
    objectives: list[Objective] = field(default_factory=list)
    # agent_key -> "hostile" | "neutral" | "allied"
    agent_stances: dict[str, str] = field(default_factory=dict)
    # hidden numeric favour per agent, -100..100 (drives stance buckets)
    agent_favor: dict[str, float] = field(default_factory=dict)
    # figure_key -> persona generated by the Cast Designer at game start
    # {traits, core_value, hidden_agenda, utility_shift} (COUNTRY_SCENARIOS.md §2.2)
    cast: dict[str, dict] = field(default_factory=dict)
    history: list[str] = field(default_factory=list)  # one terse line per resolved decision
    consumed_events: set[str] = field(default_factory=set)
    flags: dict[str, bool] = field(default_factory=dict)  # e.g. {"pla_clique_handled": True}
    # consecutive months a key indicator has been < 15 (universal collapse, §3)
    low_streak: dict[str, int] = field(default_factory=dict)
    # background effects from global events with no local hook (COUNTRY_SCENARIOS.md §2.4)
    # each: {"id", "label", "remaining", "deltas": {indicator: per-month delta}}
    active_modifiers: list[dict] = field(default_factory=list)
    rng_seed: int = 0
    game_over: str | None = None  # None while playing; otherwise an ending key
    ending_text: str = ""
    # one-shot warning the next Narrator should weave in (e.g. brewing PLA coup); cleared on use
    pending_alert: str = ""

    # -- helpers -----------------------------------------------------------------

    def get(self, key: str) -> int:
        if key in self.indicators:
            return self.indicators[key]
        return self.factions.get(key, 0)

    def apply(self, key: str, delta: float) -> int:
        """Apply a delta to an indicator or faction meter, clamped to 0..100."""
        bucket = self.indicators if key in self.indicators else self.factions
        bucket[key] = clamp(bucket.get(key, 0) + delta)
        return bucket[key]

    def history_digest(self, recent: int = 3, budget_chars: int = 700) -> str:
        """Rolling memory kept cheap for a small SLM (§6): last `recent` lines verbatim,
        the rest compressed to a single summary line."""
        if not self.history:
            return "(no decisions yet)"
        tail = self.history[-recent:]
        head = self.history[:-recent]
        parts = []
        if head:
            parts.append(f"Earlier ({len(head)} decisions): " + "; ".join(head[-4:]))
        parts.extend(tail)
        digest = " | ".join(parts)
        return digest[:budget_chars]

    def objectives_met(self) -> int:
        return sum(1 for o in self.objectives if o.is_met(self))

    def snapshot(self) -> dict[str, int]:
        return dict(self.indicators)
